version: 2.1
orbs:
  node: circleci/node@0.0.7
jobs:
  build:
    executor:
        name: node/node
        tag: "latest"
    working_directory: ~/repo

    steps:
      - checkout
      - node/with-cache:
          dir: ~/repo
          steps:
          - run: npm install
          - run:
              name: build
              command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build